"""empty message

Revision ID: 1af62aae79bf
Revises: 80356f425bb2
Create Date: 2020-07-20 17:56:52.866738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af62aae79bf'
down_revision = '80356f425bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insumo',
    sa.Column('id_insumo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_insumo', sa.String(), nullable=False),
    sa.Column('codigo_insumo', sa.Integer(), nullable=False),
    sa.Column('cantidad_insumo', sa.Integer(), nullable=False),
    sa.Column('color_insumo', sa.String(), nullable=True),
    sa.Column('medidas_insumo', sa.String(), nullable=True),
    sa.Column('marca_insumo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_insumo')
    )
    op.create_table('proveedor',
    sa.Column('id_proveedor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_empresa', sa.String(), nullable=False),
    sa.Column('rut_empresa', sa.String(), nullable=False),
    sa.Column('nombre_proveedor', sa.String(), nullable=False),
    sa.Column('apellido_proveedor', sa.String(), nullable=False),
    sa.Column('telefono_proveedor', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_proveedor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proveedor')
    op.drop_table('insumo')
    # ### end Alembic commands ###
