"""empty message

Revision ID: 7a8b07e62b26
Revises: 80356f425bb2
Create Date: 2020-07-20 15:14:38.524265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8b07e62b26'
down_revision = '80356f425bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor',
    sa.Column('id_proveedor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_empresa', sa.String(), nullable=False),
    sa.Column('rut_empresa', sa.String(), nullable=False),
    sa.Column('nombre_proveedor', sa.String(), nullable=False),
    sa.Column('apellido_proveedor', sa.String(), nullable=False),
    sa.Column('telefono_proveedor', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_proveedor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proveedor')
    # ### end Alembic commands ###
