"""empty message

Revision ID: 84c66b222208
Revises: 4737c1f9620d
Create Date: 2020-07-07 18:21:44.213234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c66b222208'
down_revision = '4737c1f9620d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('correo', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'correo')
    # ### end Alembic commands ###
