"""empty message

Revision ID: b4aab30e8c99
Revises: e85c7dc544bf
Create Date: 2020-07-22 23:46:25.903341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4aab30e8c99'
down_revision = 'e85c7dc544bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('id_producto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_producto', sa.String(), nullable=False),
    sa.Column('codigo_producto', sa.Integer(), nullable=False),
    sa.Column('color_producto', sa.String(), nullable=True),
    sa.Column('medidas_producto', sa.String(), nullable=True),
    sa.Column('marca_producto', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_producto')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto')
    # ### end Alembic commands ###
